---
title: "Visualizing Risk"
author: "John Benninghoff"
date: '2024-12-06'
date-modified: '2024-12-06'
categories: risk quantification
order: 106
output:
  html_notebook:
    theme:
      version: 5
      preset: bootstrap
    css: assets/extra.css
    pandoc_args: --shift-heading-level-by=1
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
---

An exploration of different approaches to communicating security breach risk informed by prior work.

# Questions/TODO

- [ ] How should tail risk be visualized?
- [ ] How well do quantile dotplots capture tail risk?

```{r setup, message = FALSE, warning = FALSE}
# no libraries
```

# Background

The [Risk Value Analysis](risk-value.Rmd) found that a firm's executive is unlikely to invest in
reducing the risk of a large security breach, suggesting that security spending should be presented
differently:

> At the firm level, I think this means that security leaders shouldn't present security as an
investment. As with safety, I think the main argument for better security is a moral or emotional
case: we care about security because we care about our customers, partners, and other stakeholders.
Also, people are typically loss-averse, so expressing security risk in those terms will better
connect with decision makers. Using
[Tail value at risk](https://en.wikipedia.org/wiki/Tail_value_at_risk) or
[Loss Exceedance Curves](https://www.cyentia.com/communicating-risk-loss-exceedance-curves/) express
loss in this way - "There's a 5% chance of cybersecurity losses exceeding \$780,000 and a 1% chance
of losses exceeding \$25,000,000 over the next year." I also think it means security leaders should
be mindful of *how* they spend their limited funds, by maximizing investments in
[what works](https://doi.org/10.1080/23738871.2024.2335461).

This analysis explores different approaches to communicating that risk with the goal of promoting
decisions on security spending so that all participants are satisfied with the outcome, informed by
prior work on risk communication and risk perception, including the work of
[Lace Padilla](http://www.lacepadilla.com), and Cyentia's
[analysis](https://www.youtube.com/watch?v=eiMBMsN_4j4) on tail value at risk.
